Fix build on aosp-master/mainline_modules
Apply the same default as crosvm to avoid inconsistency.

Previous error:
  error: external/libchromeos-rs/Android.bp:35:1: module "liblibchromeos"
  variant "linux_bionic_x86_64_rlib_rlib-std": depends on disabled module
  "libdata_model"

Bug: 174797066
Test: build/soong/scripts/build-mainline-modules.sh
Change-Id: I60725421b9fc40d7f30bf78eba876bb2b1adb832